### ISSUE TITLE
Are there other animals Gerry hangs out with?

### ISSUE THREAD

**Issue by schaar** [GerryGiraffe/leaves#1]
Perhaps a shark or a gorilla?

**Comment by yourfrienderin** [comment]
Bea and Wilma are best friends IRL. Maybe Gerry needs an Ostrich friend? 

![unlikely-animal-friends-2-21](https://cloud.githubusercontent.com/assets/13856868/10746444/51407ab0-7c08-11e5-8b9d-213758ca47e6.jpg)

**Comment by GerryGiraffe** [comment]
OH YEAH SHARKS ARE COOL AND GORILLAS ARE COOL AND THE COOLEST COOLS ARE LONG NECKS COOLS

**Comment by GerryGiraffe** [comment]
NOW THERE ARE MORE ANIMALS HERE AND THAT IS COOL LIKE ME, GERRY THE GIRAFFE!
